language: node_js
node_js:
- node
notifications:
  slack:
    secure: XoIVkiudsfwOXB0xWpNomeFHBdInY7m1d+ZjVn95O1KJnwtQZQwOICA+0yk5als0OcfyEPOFQSPp42TZ/5yNkTn/ej5siTyVMrD9d4e/A51Vlef6s3a+VARce/F9plgIf38V626i8eYa5slNDvs5sbyBD8C4nZPvpRl5RDDK4JEkGm+74N6UouqV8Xtgg2AVyNxVNZCE0cvtU5ioDEmR8iYMxD/0qskqlh8G+swLLk5pN2nFp8Z9OTBdxDefgTD7bIoRCZqu+omlyINr6ye1/yQL4YmGOBrTr1XKiW3f5noxDri8lxSjUbEPasNxwIhev3QZ9IV2DFE7fPnp33gmvGXUdP+1+KtdsXufclB1SstIpo22dTs9zmujo25dgL4OSMrSg9a6S7szO5Z0WM8a0qJweeUIkSPiSgVkhwEc2buGE49OTh4ZtcNvg57cUjMa1A2gVYGrHrlbi1TMVREZdKZRfPtpKMzlBAwvXAMukRSaBS8repJCZhRQeh/jboo83u5eYTVZh2yjQUyY2vlw8a6FKihYCaqa+0xm5BUbK2FJo+5I4mrnnF3wlnFOm2xz76yGtZszlSDlleaXGXHPu/OqaFe274LU//JAYMkoVc/PLu0/9P11pKnSA1YHEPLGJbhKtEfKbj8f6NIxFfwPZK6/K0bPI8ZevFcLG5HcKwk=
before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
before_script:
- npm install -g codecov
- npm install coveralls
- npm install
- yes | cp ./src/environments/environment.prod.ts ./src/environments/environment.ts
- cat ./src/environments/environment.ts
- ng lint
- ng build --aot --prod
- webdriver-manager update
- ng serve & ng e2e
- ng test --watch=false --code-coverage
script:
- codecov
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
